### ISSUE TITLE
[spoilers] Nayuta final boss bug

### ISSUE THREAD

**Issue by wavvywob** [dackst/nayuta#1]
<img width="960" alt="2020-11-04 (9)" src="https://user-images.githubusercontent.com/63887248/98119924-4907f100-1e7b-11eb-8ef1-1faddc0274d0.png">
 

as you should above the element attack names for noi's totems elemental abilities show up as jp text. This pretty much happened to me every time she used one that or nothing displayed at all. i'm assuming it's the same problem as the location text or something similar.

Thank you so much for making this though.

**Comment by dackst** [comment]
Thanks for letting me know about this. I might have seen this in my first playthrough, but I completely missed it on my most recent one, as I cheesed through the boss with the turbo button constantly held down. Anyway, the same thing happens in the original translation, so it's not something I forgot to bring over.

The location and boss text are animated, and are actually videos stored as ITV files. There's only one of these files for each boss and some locations. [In this thread](https://heroesoflegend.org/forums/viewtopic.php?f=22&t=167) there is discussion of being able to tediously edit them frame by frame, but I guess they never finished any of them. I wasn't willing to do any of that myself.

I was thinking this could instead be a static image that the previous team missed, which would be stored in either an ITP or IT3 file. However, I just opened up all the ITPs and some of the obvious IT3s (like the one for this particular boss and map) and didn't find anything, so now I'm not sure where this is stored.

**Comment by wavvywob** [comment]
lol the boss was boring af I understand fast-forwarding through it. That is weird that you can't find it perhaps it isn't an image at all or is stored in some weird place away from where it would make sense to be.

**Comment by Wandering-Heiho** [comment]
So I decided to try out Flame's tools to search a little, and I believe I may have found it.
![ef_03_21](https://user-images.githubusercontent.com/73907314/98271631-213d8980-1f5e-11eb-98a3-a4cd509b3c48.jpg)
This was located inside USRDIR\efx\tex and the file was ef_03_21.itp

Hope that helps.

**Comment by wavvywob** [comment]
That seems to be the image

**Comment by dackst** [comment]
> This was located inside USRDIR\efx\tex and the file was ef_03_21.itp

Ah, thanks, found it now. It looks like I just ended up missing it too, in the middle of hundreds of other images.

The text appears to be 雪月風花, which is [this](https://en.wikipedia.org/wiki/Snow,_Moon_and_Flowers), but with an extra character for "wind," which I assume represents summer.

I came up with a quick graphic, but looking at the first screenshot again, it looks like there was a border around the text that's now missing. I may have to play around with transparency more later. (On my first try after getting it to show up, the [text was transparent](https://user-images.githubusercontent.com/35816592/98308682-a775c200-1f96-11eb-8f05-ff5529447a43.png).)

![NPJH50625_00024](https://user-images.githubusercontent.com/35816592/98308605-76958d00-1f96-11eb-98d1-163f424cc323.png)

**Comment by dackst** [comment]
I ended up changing the text to "Four Seasons," even though it's not the same as the "Four Seasons" used in the manual, which was "四季." Since Wikipedia calls it a metonym, it's likely not literally referring to the moon and whatnot. The Japanese title for Fire Emblem: Three Houses uses the same four characters, supposedly in reference to a full year.

![NPJH50625_00027](https://user-images.githubusercontent.com/35816592/98424349-7f05ca80-205f-11eb-8440-fd7febcc3a93.png)

I was bothering me for a while that the first screenshot posted here seems to have a white border at the top that's missing here, but I tried it again with the original translation and it's still not there, so I guess it was just some of the effects of the attack going crazy.

![NPJH50625_00029](https://user-images.githubusercontent.com/35816592/98424470-cb510a80-205f-11eb-99a3-94aeca149045.png)

**Comment by Wandering-Heiho** [comment]
From what I'm remembering, there is a brief period when the text is on screen that a visual effect happens. While the effect doesn't alter the HUD, it does cause a faint offset and slight blur to everything else (notice that the edges of the platform aren't as sharp in the original image). I'm guessing that the text is an actual object instead of being part of the HUD, which is why it would also be affected by the it.
