### ISSUE TITLE
Dialogue Errors Found During Chapter 2 and Chapter 3 

### ISSUE THREAD

**Issue by Wandering-Heiho** [dackst/nayuta#10]
### Chapter 2
I think Nayuta meant to say here "I should return to Terra for now."
![NPJH50625_00000](https://user-images.githubusercontent.com/73907314/107393095-5fe86000-6ac8-11eb-9e9d-6be61138f0cc.jpg)
line 1010 in script/input/mp_0002.tsv
_____
This is a small mistake that was also in the original English Patch. Rieseweld is the northwestern continent.
![NPJH50625_00001](https://user-images.githubusercontent.com/73907314/107393365-b81f6200-6ac8-11eb-8d03-4633b782fede.jpg)
line 235 in script/input/mp_0100.tsv
_____
"the more" is repeated here.
![NPJH50625_00002](https://user-images.githubusercontent.com/73907314/107393434-ccfbf580-6ac8-11eb-9324-793cc11d0aa7.jpg)
line 120 in script/input/mp_0000.tsv
_____
### Chapter 3
Not too sure that "all" fits here after "everyone".
![NPJH50625_00000](https://user-images.githubusercontent.com/73907314/107393715-19473580-6ac9-11eb-966d-d6283e136793.jpg)
lines 410-413 in script/input/mp_0110.tsv
_____
I feel this could be changed a couple different ways, as the current line feels a little clunky to me.
"Then let's all go to the Astrolabe."
or
"Then all three of us will go to the Astrolabe."
![NPJH50625_00001](https://user-images.githubusercontent.com/73907314/107393755-25cb8e00-6ac9-11eb-8632-5f4b8d4c8241.jpg)
line 1245 in script/input/mp_0101.tsv
_____
This line seemed a little odd to me, as I'm not entirely sure why she would think that the gloomy atmosphere was cause by her.
I decided to try taking the original Japanese dialogue and putting it into DeepL. While it sometimes gave me a very similar result to what is already here, it sometimes had the line refering to Nayuta's mood (this also seems to match up better with what Horolo comments about when completing the sidequest).
![NPJH50625_00002](https://user-images.githubusercontent.com/73907314/107393881-4267c600-6ac9-11eb-86c6-b65b6bdf44ad.jpg)
![NPJH50625_00002_DeepL](https://user-images.githubusercontent.com/73907314/107393885-4398f300-6ac9-11eb-96eb-23cedfa6748f.png)
![NPJH50625_00003](https://user-images.githubusercontent.com/73907314/107393886-4398f300-6ac9-11eb-96db-e82a84f10295.jpg)
line 953 in script/input/mp_0000.tsv
_____
Probably the funniest one I've come across. When collecting the yellow pigment, it seems that Nayuta says Noi's line followed by Noi saying Nayuta's line. From looking at the .tsv, it seems that this is from the character's names being swapped compared to getting the red and blue pigments.
![NPJH50625_00004](https://user-images.githubusercontent.com/73907314/107393968-5c090d80-6ac9-11eb-9404-ce7c7840ca31.jpg)
lines 97-103 in script/input/mp_3002d.tsv
_____
I believe "left" should be "leave" in this sentence.
![NPJH50625_00005](https://user-images.githubusercontent.com/73907314/107394006-65927580-6ac9-11eb-8ea9-3282196cdc19.jpg)
line 837 in script/input/mp_3099.tsv
_____
I think this is supposed to be "Well, I think it'd be better"
![NPJH50625_00006](https://user-images.githubusercontent.com/73907314/107394683-231d6880-6aca-11eb-8a95-810ef31f1eb5.jpg)
line 2440 in script/input/mp_0110.tsv
_____
### Various Warden Conversations
I decided to go through the earlier parts of the game on a first playthrough to see if there was anything that I would have missed.

I believe the order of "been" and "just" should be swapped.
![NPJH50625_00000](https://user-images.githubusercontent.com/73907314/107395581-f158d180-6aca-11eb-8aff-4acbc9b323ba.jpg)
lines 29 in script/input/mp_2099.tsv
_____
I think there is supposed to be an "is" after "...This"
![NPJH50625_00001](https://user-images.githubusercontent.com/73907314/107395604-f7e74900-6aca-11eb-8814-fa5add9b7aae.jpg)
line 177 in script/input/mp_3002c.tsv
_____
Based on what is said before and after this line, it seems that Nayuta meant to say something like "Yeah... Could you assist us?"
![NPJH50625_00002](https://user-images.githubusercontent.com/73907314/107395647-02094780-6acb-11eb-9fa6-58c6475f499f.jpg)
line 68 in script/input/mp_5100.tsv
_____
I think putting a "to" after "able" would make this work better.
![NPJH50625_00003](https://user-images.githubusercontent.com/73907314/107395675-07ff2880-6acb-11eb-99a4-cc176515df45.jpg)
lines 89 in script/input/mp_5100.tsv
_____
### Miscellaneous
I'm pretty sure the plural form of tornado is tornadoes.
![NPJH50625_00000](https://user-images.githubusercontent.com/73907314/107395831-2bc26e80-6acb-11eb-98a5-922b362d59d2.jpg)
lines 516 in text/input/monslib.tsv
_____
Lastly, I took a brief look at the text/input/questlib.tsv and I noticed that the recently name changed stages like Fruitful Hermit's Way is still called Hermit's Path. These were all of the instances and other errors I could find in the file.

- At line 337, Fruitful Hermit's Way is called Hermit's Path.
- At lines 244 and 341, Scrying Pool Cavern is called Scrying Pool Caves.
- At lines 206 and 228, Dragon River Grotto is called Dragon River Cavern.
- At lines 306 and 345, Canyon of Biting Wind is called Wind Cutting Valley.
- At line 469, I think "thats" is supposed to be "that".

**Comment by dackst** [comment]
> I think Nayuta meant to say here "I should return to Terra for now."

This occurs in the the beginning of Chapter 2, where, after Noi goes to mess with the Astrolabe and has Nayuta wait in the garden, Nayuta ditches her to search Remnant Island for Cygna instead. It's a little weird that it doesn't update after meeting up again with Noi outside Nayuta's house, but it would immediately update again after the scene one screen transition away anyway.

---

> This line seemed a little odd to me, as I'm not entirely sure why she would think that the gloomy atmosphere was cause by her.
> I decided to try taking the original Japanese dialogue and putting it into DeepL. While it sometimes gave me a very similar result to what is already here, it sometimes had the line refering to Nayuta's mood (this also seems to match up better with what Horolo comments about when completing the sidequest).

Due to Japanese allowing subjects of a sentence to be implicit and omitted entirely, DeepL will try to add them in when translating to English, which doesn't. It seems to allow the sentence to use a "you" (which would refer to Nayuta), "I" (which would refer to Horolo), or a more generally subjunctive "it". It's entirely context based which is most "correct". The line at the end explicitly states something along the lines of "you and other people of the village" with "キミも村の人たちも", so Nayuta isn't the only one who's visibly not happy at the moment.

I interpreted the "Sorry" to be an expression of sympathy rather than guilt, the same way someone might say "sorry" after learning of something bad happening, but not confessing that they caused it to happen themselves. But given the "If you don't mind" immediately following this line, I guess it might make more sense to be something along the lines of "sorry to bother you" or "sorry to ask this of you".

---

> Probably the funniest one I've come across. When collecting the yellow pigment, it seems that Nayuta says Noi's line followed by Noi saying Nayuta's line. From looking at the .tsv, it seems that this is from the character's names being swapped compared to getting the red and blue pigments.

The character names in the third columns of the .tsv files aren't actually used for anything. It seems the original translation made the first two lines of each of these events identical (besides the names of the colors) when they weren't in Japanese, and I never noticed. For example, Nayuta's name is only said in the red one.

---

> I believe the order of "been" and "just" should be swapped.

I was thinking the "just" here was meant to modify the "left" here. As in, after the antagonists go through the trouble of stealing them from Noi before the start of the game and crippling her powers, the Master Gears are then being unceremoniously abandoned for some unknown reason. Unless I'm missing some other reason why they should be swapped? 

---

> Based on what is said before and after this line, it seems that Nayuta meant to say something like "Yeah... Could you assist us?"

The original translation is "Yes...Do you know of any method by which we can do this?" and the Japanese is "ええ……ギオさんたちは	何か、いい方法を知りませんか？" [知](https://en.wiktionary.org/wiki/知) has to do with knowing things. He's explicitly asking for knowledge rather than for them to help magically levitate him up or something.

---

>     * At line 337, Fruitful Hermit's Way is called Hermit's Path.
>     * At lines 244 and 341, Scrying Pool Cavern is called Scrying Pool Caves.
>     * At lines 206 and 228, Dragon River Grotto is called Dragon River Cavern.
>     * At lines 306 and 345, Canyon of Biting Wind is called Wind Cutting Valley.
>     * At line 469, I think "thats" is supposed to be "that".

Are you sure you weren't looking at some older version of the file? All the dungeon names in `questlib.tsv` were [already changed](https://github.com/dackst/nayuta/commit/bfbf880b80e92837a6cb1cc26392cdbedc95612b#diff-9f590f1b59f991d0cf4e5e8b8051e5143e19cf62cb1f874546662b9dbbe29a29) at the same time they were changed elsewhere. The "thats" was also changed [here](https://github.com/dackst/nayuta/commit/f9c1cc21e2c722b2a0c8f0c9ab3390fc647cc532#diff-9f590f1b59f991d0cf4e5e8b8051e5143e19cf62cb1f874546662b9dbbe29a29).

**Comment by Wandering-Heiho** [comment]
> I was thinking the "just" here was meant to modify the "left" here. As in, after the antagonists go through the trouble of stealing them from Noi before the start of the game and crippling her powers, the Master Gears are then being unceremoniously abandoned for some unknown reason. Unless I'm missing some other reason why they should be swapped?
That makes sense. I wasn't thinking about that when I came across the dialogue.
____
> Are you sure you weren't looking at some older version of the file? All the dungeon names in questlib.tsv were already changed at the same time they were changed elsewhere. The "thats" was also changed here.
It turns out that I was looking at an older version of it. Apologies for that.

**Comment by wad11656** [comment]
Another vote for "All the Master Gears up until now have **just been** left at the altars" or  "All the Master Gears up until now have **simply been** left at the altars". I wish I had the knowledge and vocabulary to confirm its grammatical correctness, but fwiw the way it's worded now sounds incorrect to me

**Comment by dackst** [comment]
Especially since it's spoken dialogue from a relatively informal character (compared to the other wardens that are not Noi), I'm more concerned about whether it "sounds" right rather than any sort of grammatical correctness.

Thinking about it again, the sentence sounds pretty much the same to me either way. Hopefully this version has less potential to be awkward sounding.
